###############################################################################
# Columns
###############################################################################
SYMP_COLS = [
    "esas_pain",
    "esas_tiredness",
    "esas_nausea",
    "esas_depression",
    "esas_anxiety",
    "esas_drowsiness",
    "esas_appetite",
    "esas_well_being",
    "esas_shortness_of_breath",
]
LAB_COLS = [
    "activated_partial_thromboplastin_time",
    "alanine_aminotransferase",
    "albumin",
    "alkaline_phosphatase",
    "aspartate_aminotransferase",
    "basophil",
    "bicarbonate",
    "calcium",
    "carbohydrate_antigen_19-9",
    "chloride",
    "creatinine",
    "eosinophil",
    "estimated_glomerular_filtration_rate",	
    "glucose",
    "hematocrit",
    "hemoglobin",
    "lactate_dehydrogenase",
    "lymphocyte",
    "magnesium",
    "mean_corpuscular_hemoglobin",
    "mean_corpuscular_hemoglobin_concentration",
    "mean_corpuscular_volume",
    "mean_platelet_volume",
    "monocyte",
    "neutrophil",
    "phosphate",
    "platelet",
    "potassium",
    "prothrombin_time_international_normalized_ratio",
    "red_blood_cell",
    "red_cell_distribution_width",
    "sodium",
    "total_bilirubin",
    "white_blood_cell",
]
SYMP_CHANGE_COLS = [f"{col}_change" for col in SYMP_COLS]
LAB_CHANGE_COLS = [f"{col}_change" for col in LAB_COLS]
DRUG_COLS = [
    '%_ideal_dose_given_GEMCITABINE',
    '%_ideal_dose_given_CISPLATIN',
    '%_ideal_dose_given_FLUOROURACIL',
    '%_ideal_dose_given_ETOPOSIDE',
    '%_ideal_dose_given_CARBOPLATIN',
    '%_ideal_dose_given_PEMETREXED',
    '%_ideal_dose_given_OXALIPLATIN',
    '%_ideal_dose_given_VINORELBINE',
    '%_ideal_dose_given_IRINOTECAN',
    '%_ideal_dose_given_PACL',
    '%_ideal_dose_given_NAB-PACL',
    '%_ideal_dose_given_PEMBROLIZUMAB',
    '%_ideal_dose_given_NIVOLUMAB',
    '%_ideal_dose_given_DOCETAXEL',
    '%_ideal_dose_given_EPIRUBICIN',
    '%_ideal_dose_given_TRASTUZUMAB',
    '%_ideal_dose_given_CYCLOPHOSPHAMIDE',
    '%_ideal_dose_given_DOXORUBICIN',
    '%_ideal_dose_given_DURVALUMAB',
    '%_ideal_dose_given_BEVACIZUMAB',
    '%_ideal_dose_given_CETUXIMAB',
    '%_ideal_dose_given_RAMUCIRUMAB',
    '%_ideal_dose_given_RALTITREXED',
    '%_ideal_dose_given_TREMELIMUMAB',
    '%_ideal_dose_given_PERTUZUMAB',
    '%_ideal_dose_given_TOPOTECAN',
    '%_ideal_dose_given_LIPOSOMAL IRINOTECAN',
    '%_ideal_dose_given_ATEZOLIZUMAB',
    '%_ideal_dose_given_IPILIMUMAB',
    '%_ideal_dose_given_MITOMYCIN',
    '%_ideal_dose_given_PANITUMUMAB',
    '%_ideal_dose_given_CAPECITABINE',
    '%_ideal_dose_given_ERLOTINIB',
    '%_ideal_dose_given_LENVATINIB',
    '%_ideal_dose_given_OLAPARIB',
]

# default columns for data transformations
# imputation
DEFAULT_IMPUTE_COLS = {
    "mean": LAB_COLS + LAB_CHANGE_COLS,
    "most_frequent": SYMP_COLS
    + SYMP_CHANGE_COLS
    + ["patient_ecog", "patient_ecog_change"],
    "median": [],
}
# one-hot encoding
DEFAULT_ENCODE_COLS = ["regimen", "intent"]
# outlier clipping
DEFAULT_CLIP_COLS = (
    ["body_surface_area", "height", "weight"] + LAB_COLS + LAB_CHANGE_COLS
)
# normalization
DEFAULT_NORM_COLS = (
    [
        "age",
        "body_surface_area",
        "cycle_number",
        "days_since_last_treatment",
        "days_since_prev_ED_visit",
        "days_since_starting_treatment",
        "height",
        "line_of_therapy",
        "num_prior_ED_visits_within_5_years",
        "patient_ecog",
        "patient_ecog_change",
        "visit_month_sin",
        "visit_month_cos",
        "weight",
    ]
    + DRUG_COLS
    + LAB_COLS
    + LAB_CHANGE_COLS
    + SYMP_COLS
    + SYMP_CHANGE_COLS
)


###############################################################################
# Mappings
###############################################################################
# cancer site / cancer morphology
CANCER_CODE_MAP = {
    "C00": "Lip",
    "C01": "Base of tongue",
    "C02": "Other and unspecified parts of tongue",
    "C03": "Gum",
    "C04": "Floor of mouth",
    "C05": "Palate",
    "C06": "Other and unspecified parts of mouth",
    "C07": "Parotid gland",
    "C08": "Other and unspecified major salivary glands",
    "C09": "Tonsil",
    "C10": "Oropharynx",
    "C11": "Nasopharynx",
    "C12": "Pyriform sinus",
    "C13": "Hypopharynx",
    "C14": "Other and ill-defined sites in lip, oral cavity, and pharynx",
    "C15": "Esophagus",
    "C16": "Stomach",
    "C17": "Small intestine",
    "C18": "Colon",
    "C19": "Rectosigmoid junction",
    "C20": "Rectum",
    "C21": "Anus and anal canal",
    "C22": "Liver and intrahepatic bile ducts",
    "C23": "Gallbladder",
    "C24": "Other and unspecified parts of biliary tract",
    "C25": "Pancreas",
    "C26": "Other and ill-defined digestive organs",
    "C30": "Nasal cavity and middle ear",
    "C31": "Accessory sinuses",
    "C32": "Larynx",
    "C33": "Trachea",
    "C34": "Bronchus and lung",
    "C37": "Thymus",
    "C38": "Heart, mediastinum, and pleura",
    "C40": "Bones, joints, and articular cartilage of limbs",
    "C41": "Bones, joints, and articular cartilage of other and unspecified sites",
    "C44": "Skin",
    "C47": "Peripheral nerves and autonomic nervous system",
    "C48": "Retroperitoneum and peritoneum",
    "C49": "Connective, subcataneous, and other soft tissues",
    "C50": "Breast",
    "C51": "Vulva",
    "C52": "Vagina",
    "C53": "Cervix uteri",
    "C54": "Corpus uteri",
    "C55": "Uterus, NOS",
    "C56": "Ovary",
    "C57": "Other and unspecified female genital organs",
    "C58": "Placenta",
    "C60": "Penis",
    "C61": "Prostate gland",
    "C62": "Testis",
    "C63": "Other and unspecified male genital organs",
    "C64": "Kidney",
    "C65": "Renal pelvis",
    "C66": "Ureter",
    "C67": "Bladder",
    "C68": "Other and unspecified urinary organs",
    "C69": "Eye and adnexa",
    "C71": "Brain",
    "C72": "Spinal cord, cranial nerves, and other parts of central nervous system",
    "C73": "Thyroid and other endocrine glands",
    "C74": "Adrenal Gland",
    "C75": "Other endocrine glands and related structures",
    "C76": "Other and ill-defined sites",
    "C80": "Unknown primary site",
    "800": "Neoplasms, NOS",
    "801": "Epithelial neoplasms, NOS",
    "802": "Epithelial neoplasms, NOS",
    "803": "Epithelial neoplasms, NOS",
    "804": "Epithelial neoplasms, NOS",
    "805": "Squamous cell neoplasms",
    "807": "Squamous cell neoplasms",
    "808": "Squamous cell neoplasms",
    "809": "Basal cell neoplasms",
    "812": "Transitional cell papillomas and carcinomas",
    "813": "Transitional cell papillomas and carcinomas",
    "814": "Adenomas and adenocarcinomas",
    "816": "Adenomas and adenocarcinomas",
    "817": "Adenomas and adenocarcinomas",
    "818": "Adenomas and adenocarcinomas",
    "820": "Adenomas and adenocarcinomas",
    "821": "Adenomas and adenocarcinomas",
    "823": "Adenomas and adenocarcinomas",
    "824": "Adenomas and adenocarcinomas",
    "825": "Adenomas and adenocarcinomas",
    "826": "Adenomas and adenocarcinomas",
    "829": "Adenomas and adenocarcinomas",
    "831": "Adenomas and adenocarcinomas",
    "832": "Adenomas and adenocarcinomas",
    "833": "Adenomas and adenocarcinomas",
    "834": "Adenomas and adenocarcinomas",
    "837": "Adenomas and adenocarcinomas",
    "838": "Adenomas and adenocarcinomas",
    "840": "Adnexal and skin appendage neoplasms",
    "843": "Mucoepidermoid neoplasms",
    "844": "Cystic, mucinous, and serous neoplasms",
    "845": "Cystic, mucinous, and serous neoplasms",
    "846": "Cystic, mucinous, and serous neoplasms",
    "847": "Cystic, mucinous, and serous neoplasms",
    "848": "Cystic, mucinous, and serous neoplasms",
    "849": "Cystic, mucinous, and serous neoplasms",
    "850": "Ductal and lobular neoplasms",
    "851": "Ductal and lobular neoplasms",
    "852": "Ductal and lobular neoplasms",
    "853": "Ductal and lobular neoplasms",
    "854": "Ductal and lobular neoplasms",
    "855": "Acinar cell neoplasms",
    "856": "Complex epithelial neoplasms",
    "857": "Complex epithelial neoplasms",
    "858": "Thymic epithelial neoplasms",
    "862": "Specialized gonadal neoplasms",
    "872": "Paragangliomas and glomus tumors",
    "873": "Nevi and melanomas",
    "874": "Nevi and melanomas",
    "877": "Nevi and melanomas",
    "880": "Soft tissue tumors and sarcomas, NOS",
    "881": "Fibromatous neoplasms",
    "883": "Fibromatous neoplasms",
    "885": "Lipomatous neoplasms",
    "889": "Myomatous neoplasms",
    "890": "Myomatous neoplasms",
    "891": "Myomatous neoplasms",
    "892": "Myomatous neoplasms",
    "893": "Complex mixed and stromal neoplasms",
    "894": "Complex mixed and stromal neoplasms",
    "895": "Complex mixed and stromal neoplasms",
    "898": "Complex mixed and stromal neoplasms",
    "902": "Fibroepithelial neoplasms",
    "904": "Synovial-like neoplasms",
    "905": "Mesothelial neoplasms",
    "906": "Germ cell neoplasms",
    "907": "Germ cell neoplasms",
    "908": "Germ cell neoplasms",
    "910": "Trophoblastic neoplasms",
    "911": "Mesonephromas",
    "912": "Blood vessel tumors",
    "914": "Blood vessel tumors",
    "915": "Blood vessel tumors",
    "918": "Osseous and chondromatous neoplasms",
    "922": "Osseous and chondromatous neoplasms",
    "924": "Osseous and chondromatous neoplasms",
    "926": "Miscellaneous bone tumors",
    "936": "Miscellaneous tumors",
    "938": "Gliomas",
    "940": "Gliomas",
    "942": "Gliomas",
    "944": "Gliomas",
    "945": "Gliomas",
    "947": "Gliomas",
    "954": "Nerve sheath tumors",
    "956": "Nerve sheath tumors",
}

# units
UNIT_MAP = {
    "L/L": ["hematocrit"],
    "U/L": [
        "alanine_aminotransferase",
        "alkaline_phosphatase",
        "aspartate_aminotransferase",
        "lactate_dehydrogenase",
    ],
    "cm": ["height"],
    "fL": ["mean_corpuscular_volume", "mean_platelet_volume"],
    "g/L": ["albumin", "hemoglobin", "mean_corpuscular_hemoglobin_concentration"],
    "kg": ["weight"],
    "kU/L": ["carbohydrate_antigen_19-9"],
    "mL/min/1.73m2": ["eGFR"],
    "mmol/L": [
        "bicarbonate",
        "calcium",
        "chloride",
        "glucose",
        "magnesium",
        "phosphate",
        "potassium",
        "sodium",
    ],
    "m^2": ["body_surface_area"],
    "pg": ["mean_corpuscular_hemoglobin"],
    "s": ["activated_partial_thromboplastin_time"],
    "umol/L": ["creatinine", "total_bilirubin"],
    "x10e9/L": [
        "basophil",
        "eosinophil",
        "lymphocyte",
        "monocyte",
        "neutrophil",
        "platelet",
        "white_blood_cell",
    ],
    "x10e12/L": ["red_blood_cell"],
    "years": ["age"],
    "%CV": ["red_cell_distribution_width"],
}